language: node_js

node_js:
  - 8
  - 10
  - 12

sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  global:
    - TEST=1

matrix:
  fast_finish: true

  include:
    - node_js: 10
      env: TEST=0 LINT=1

script:
  - sh -c "if [ '$LINT' = '1' ]; then yarn lint; fi"
  - commitlint-travis

notifications:
  email: false

after_success:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote add -f pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git checkout master

deploy:
  - provider: script
    script: npx lerna publish --yes --git-remote pub
    skip_cleanup: true
    keep_history: true
    on:
      branch: master